alter table public.buyer_profiles enable row level security;
alter table public.buyer_profiles force row level security;
alter table public.vehicle_brands enable row level security;
alter table public.vehicle_brands force row level security;
alter table public.piece_categories enable row level security;
alter table public.piece_categories force row level security;
alter table public.piece_category_keywords enable row level security;
alter table public.piece_category_keywords force row level security;
alter table public.vehicles enable row level security;
alter table public.vehicles force row level security;
alter table public.quotes enable row level security;
alter table public.quotes force row level security;
alter table public.quote_conditions enable row level security;
alter table public.quote_conditions force row level security;
alter table public.quote_items enable row level security;
alter table public.quote_items force row level security;
alter table public.quote_item_photos enable row level security;
alter table public.quote_item_photos force row level security;
alter table public.event_ingest enable row level security;
alter table public.event_ingest force row level security;
revoke all on public.buyer_profiles from anon, authenticated;
revoke all on public.vehicle_brands from anon, authenticated;
revoke all on public.piece_categories from anon, authenticated;
revoke all on public.piece_category_keywords from anon, authenticated;
revoke all on public.vehicles from anon, authenticated;
revoke all on public.quotes from anon, authenticated;
revoke all on public.quote_conditions from anon, authenticated;
revoke all on public.quote_items from anon, authenticated;
revoke all on public.quote_item_photos from anon, authenticated;
revoke all on public.event_ingest from anon, authenticated;
grant select, insert, update on public.buyer_profiles to authenticated;
grant select, insert on public.vehicles to authenticated;
grant select, insert on public.quotes to authenticated;
grant select, insert on public.quote_conditions to authenticated;
grant select, insert on public.quote_items to authenticated;
grant select, insert on public.quote_item_photos to authenticated;
grant insert on public.event_ingest to anon, authenticated;
create policy buyer_profiles_self_select on public.buyer_profiles for select to authenticated using (profile_id = private.current_profile_id());
create policy buyer_profiles_self_write on public.buyer_profiles for all to authenticated using (profile_id = private.current_profile_id() and private.quote_submission_context_enabled()) with check (profile_id = private.current_profile_id() and private.quote_submission_context_enabled());
create policy vehicles_owner_select on public.vehicles for select to authenticated using (buyer_id = private.current_profile_id() and deleted_at is null);
create policy vehicles_owner_insert on public.vehicles for insert to authenticated with check (buyer_id = private.current_profile_id() and private.quote_submission_context_enabled());
create policy quotes_owner_select on public.quotes for select to authenticated using (buyer_id = private.current_profile_id() and deleted_at is null);
create policy quotes_owner_insert on public.quotes for insert to authenticated with check (buyer_id = private.current_profile_id() and private.quote_submission_context_enabled());
create policy quote_conditions_owner_select on public.quote_conditions for select to authenticated using (exists (select 1 from public.quotes q where q.id = quote_id and q.buyer_id = private.current_profile_id() and q.deleted_at is null));
create policy quote_conditions_owner_insert on public.quote_conditions for insert to authenticated with check (private.quote_submission_context_enabled() and exists (select 1 from public.quotes q where q.id = quote_id and q.buyer_id = private.current_profile_id() and q.deleted_at is null));
create policy quote_items_owner_select on public.quote_items for select to authenticated using (deleted_at is null and exists (select 1 from public.quotes q where q.id = quote_id and q.buyer_id = private.current_profile_id() and q.deleted_at is null));
create policy quote_items_owner_insert on public.quote_items for insert to authenticated with check (private.quote_submission_context_enabled() and exists (select 1 from public.quotes q where q.id = quote_id and q.buyer_id = private.current_profile_id() and q.deleted_at is null));
create policy quote_item_photos_owner_select on public.quote_item_photos for select to authenticated using (deleted_at is null and exists (select 1 from public.quote_items qi join public.quotes q on q.id = qi.quote_id where qi.id = quote_item_id and qi.deleted_at is null and q.buyer_id = private.current_profile_id() and q.deleted_at is null));
create policy quote_item_photos_owner_insert on public.quote_item_photos for insert to authenticated with check (private.quote_submission_context_enabled() and exists (select 1 from public.quote_items qi join public.quotes q on q.id = qi.quote_id where qi.id = quote_item_id and q.buyer_id = private.current_profile_id() and q.deleted_at is null));
create policy event_ingest_anon_insert on public.event_ingest for insert to anon, authenticated with check (event_name in ('quote_started', 'vehicle_added') and anonymous_session_id is not null and draft_id is not null and pg_column_size(metadata) <= 4096);
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('quote-photos','quote-photos',false,6291456,array['image/jpeg','image/png','image/webp']) on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
create policy quote_photos_owner_insert on storage.objects for insert to authenticated with check (bucket_id = 'quote-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy quote_photos_owner_select on storage.objects for select to authenticated using (bucket_id = 'quote-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy quote_photos_owner_delete on storage.objects for delete to authenticated using (bucket_id = 'quote-photos' and (storage.foldername(name))[1] = auth.uid()::text);
insert into public.piece_categories (key, name) values ('lighting','Iluminação'),('body','Lataria'),('engine','Motor'),('suspension','Suspensão'),('brakes','Freios'),('electrical','Elétrica'),('trim','Acabamento'),('glass','Vidros') on conflict (key) do nothing;
insert into public.piece_category_keywords (category_id, keyword)
select pc.id, kw.keyword from public.piece_categories pc join (values
('lighting','farol'),('lighting','lanterna'),('lighting','milha'),('body','capô'),('body','capo'),('body','paralama'),('body','para-choque'),('body','parachoque'),('body','porta'),('body','grade'),('engine','motor'),('engine','cabeçote'),('engine','cabecote'),('engine','radiador'),('suspension','amortecedor'),('suspension','bandeja'),('suspension','pivô'),('suspension','pivo'),('brakes','disco de freio'),('brakes','pastilha'),('brakes','pinça'),('brakes','pinca'),('electrical','alternador'),('electrical','motor de partida'),('electrical','módulo'),('electrical','modulo'),('trim','retrovisor'),('trim','maçaneta'),('trim','macaneta'),('trim','painel'),('glass','vidro'),('glass','para-brisa'),('glass','parabrisa')) as kw(category_key, keyword) on kw.category_key = pc.key on conflict (category_id, keyword) do nothing;