'use client';
import { useEffect,useMemo,useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';
import { CONDITION_LABELS,kmLabel } from '@/lib/sprint2/format';

type Detail={opportunity:any;quote:any;vehicle:any;items:any[];conditions:any[];photoUrls:Record<string,string>};
export default function OpportunityDetail(){
 const {id}=useParams<{id:string}>(); const supabase=useMemo(()=>createClient(),[]); const [d,setD]=useState<Detail|null>(null); const [message,setMessage]=useState('Carregando…');
 useEffect(()=>{(async()=>{const {data:u}=await supabase.auth.getUser(); if(!u.user){location.href=`/auth/login?next=/supplier/opportunities/${id}`;return;} const {error:viewError}=await supabase.rpc('view_opportunity',{p_opportunity_id:id}); if(viewError){setMessage('Oportunidade indisponível.');return;} const {data:o}=await supabase.from('opportunities').select('*').eq('id',id).single(); if(!o)return; const {data:q}=await supabase.from('quotes').select('id,city,state,accepts_shipping,vehicle_id').eq('id',o.quote_id).single(); const [{data:v},{data:items},{data:conds}]=await Promise.all([supabase.from('vehicles').select('brand_name,model,year,version').eq('id',q.vehicle_id).single(),supabase.from('quote_items').select('id,piece_name,side,notes').eq('quote_id',q.id).order('sort_order'),supabase.from('quote_conditions').select('condition').eq('quote_id',q.id)]); const photos:Record<string,string>={}; for(const item of items??[]){const {data:p}=await supabase.from('quote_item_photos').select('storage_key').eq('quote_item_id',item.id); for(const ph of p??[]){const {data:signed}=await supabase.storage.from('quote-photos').createSignedUrl(ph.storage_key,120); if(signed?.signedUrl)photos[item.id]=signed.signedUrl;}}
 setD({opportunity:o,quote:q,vehicle:v,items:items??[],conditions:conds??[],photoUrls:photos});setMessage('');})();},[id,supabase]);
 async function decline(){const {error}=await supabase.rpc('decline_opportunity',{p_opportunity_id:id}); if(error){setMessage(error.message);return;} setMessage('Oportunidade recusada.');}
 if(!d)return <main className="min-h-screen bg-[#f6f2e9] p-6">{message}</main>;
 return <main className="min-h-screen bg-[#f6f2e9] text-[#1b1d22]"><section className="mx-auto max-w-3xl px-5 py-8"><Link href="/supplier/opportunities" className="text-sm font-bold text-black/50">← Oportunidades</Link><div className="mt-5 rounded-[2rem] bg-white p-6 shadow-sm md:p-9"><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-600">Cotação recebida</p><h1 className="mt-2 text-3xl font-black">{d.vehicle.brand_name} {d.vehicle.model} {d.vehicle.year}</h1><p className="mt-1 text-black/55">{d.vehicle.version}</p><div className="mt-6 grid gap-3 rounded-2xl bg-[#f6f2e9] p-4 text-sm md:grid-cols-3"><span>📍 {d.quote.city}/{d.quote.state}</span><span>Raio: {kmLabel(d.opportunity.distance_km)}</span><span>{d.quote.accepts_shipping?'Aceita envio':'Somente região'}</span></div><h2 className="mt-8 text-lg font-black">Peças solicitadas</h2><div className="mt-3 grid gap-3">{d.items.map(i=><div key={i.id} className="rounded-2xl border border-black/10 p-4"><b>{i.piece_name}</b>{i.side&&<span className="ml-2 text-sm text-black/50">· {i.side}</span>}{i.notes&&<p className="mt-2 text-sm text-black/60">{i.notes}</p>}{d.photoUrls[i.id]&&<img data-testid="quote-photo" alt="Foto enviada pelo comprador" src={d.photoUrls[i.id]} className="mt-3 h-32 w-32 rounded-xl object-cover"/>}</div>)}</div><h2 className="mt-8 text-lg font-black">Condições aceitas</h2><div className="mt-3 flex flex-wrap gap-2">{d.conditions.map(c=><span key={c.condition} className="rounded-full bg-orange-50 px-3 py-2 text-sm font-bold text-orange-800">{CONDITION_LABELS[c.condition]??c.condition}</span>)}</div><div className="mt-9 grid gap-3 md:grid-cols-2"><button data-testid="have-part" onClick={()=>setMessage('Proposta entra na Sprint 3. Nenhuma proposta foi criada.')} className="rounded-2xl bg-orange-600 px-5 py-4 font-black text-white">TENHO ESSA PEÇA</button><button data-testid="decline" onClick={decline} className="rounded-2xl border border-black/15 px-5 py-4 font-black">NÃO TENHO</button></div>{message&&<p data-testid="action-message" className="mt-4 text-sm font-bold text-black/60">{message}</p>}<p data-testid="privacy-note" className="mt-7 border-t border-black/10 pt-5 text-xs text-black/45">Dados pessoais do comprador permanecem protegidos. Aqui aparece somente o necessário para cotar.</p></div></section></main>;
}
